// SPDX-License-Identifier: GPL-3.0-or-later
// The Moment — derived from FilaBridge (https://github.com/needo37/filabridge)
// Copyright (C) 2026 maudy2u

package main

// =============================================================================
// filament_calibration_gcode_test.go
// =============================================================================
// Unit tests for the "populate calibration from print" feature:
//   - ParseCalibrationFromGcode: config-dump comment parsing, per-extruder list
//     indexing, '%' stripping, out-of-range toolIndex fallback
//   - GetCalibrationCandidates / GetCalibrationSource: DB + Spoolman lookups
//
// Run: go test ./... -v -run TestParseCalibrationFromGcode
// Run: go test ./... -v -run TestGetCalibration
// =============================================================================

import (
	"fmt"
	"net/http"
	"net/http/httptest"
	"testing"
)

// sampleConfigDump mirrors the confirmed OrcaSlicer config-dump footer lines from a real
// sliced file (see plan: KITCHE~1.GCO), used across the parser tests below.
const sampleConfigDump = `
; generated by OrcaSlicer
; some_unrelated_setting = ignored
; filament_max_volumetric_speed = 18,16
; pressure_advance = 0.0264,0.02
; filament_flow_ratio = 0.95,0.95
; bridge_flow = 1
; bridge_density = 100%
; retraction_length = 0.7
; retraction_speed = 45
`

func TestParseCalibrationFromGcode_ToolIndex0(t *testing.T) {
	got := ParseCalibrationFromGcode([]byte(sampleConfigDump), 0)
	want := map[string]string{
		"cal_max_flow_rate":     "18",
		"cal_pressure_advance":  "0.0264",
		"cal_flow_ratio":        "0.95",
		"cal_bridge_flow_ratio": "1",
		"cal_bridge_density":    "100",
		"cal_retraction_length": "0.7",
		"cal_retraction_speed":  "45",
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("%s = %q, want %q", k, got[k], v)
		}
	}
	if len(got) != len(want) {
		t.Errorf("got %d keys, want %d: %v", len(got), len(want), got)
	}
}

func TestParseCalibrationFromGcode_ToolIndex1(t *testing.T) {
	got := ParseCalibrationFromGcode([]byte(sampleConfigDump), 1)
	// Per-extruder lists select index 1; bridge_flow/bridge_density are global
	// (not per-extruder) and must stay the same regardless of toolIndex.
	if got["cal_max_flow_rate"] != "16" {
		t.Errorf("cal_max_flow_rate = %q, want %q", got["cal_max_flow_rate"], "16")
	}
	if got["cal_pressure_advance"] != "0.02" {
		t.Errorf("cal_pressure_advance = %q, want %q", got["cal_pressure_advance"], "0.02")
	}
	if got["cal_flow_ratio"] != "0.95" {
		t.Errorf("cal_flow_ratio = %q, want %q", got["cal_flow_ratio"], "0.95")
	}
	if got["cal_bridge_flow_ratio"] != "1" {
		t.Errorf("cal_bridge_flow_ratio = %q, want %q", got["cal_bridge_flow_ratio"], "1")
	}
	if got["cal_bridge_density"] != "100" {
		t.Errorf("cal_bridge_density = %q, want %q", got["cal_bridge_density"], "100")
	}
}

func TestParseCalibrationFromGcode_OutOfRangeToolIndexFallsBackToZero(t *testing.T) {
	got := ParseCalibrationFromGcode([]byte(sampleConfigDump), 5)
	if got["cal_max_flow_rate"] != "18" {
		t.Errorf("cal_max_flow_rate = %q, want %q (fallback to index 0)", got["cal_max_flow_rate"], "18")
	}
	got2 := ParseCalibrationFromGcode([]byte(sampleConfigDump), -1)
	if got2["cal_max_flow_rate"] != "18" {
		t.Errorf("cal_max_flow_rate (negative index) = %q, want %q (fallback to index 0)", got2["cal_max_flow_rate"], "18")
	}
}

func TestParseCalibrationFromGcode_MissingKeysOmitted(t *testing.T) {
	got := ParseCalibrationFromGcode([]byte("; nothing_relevant = here\n"), 0)
	if len(got) != 0 {
		t.Errorf("expected no keys found, got %v", got)
	}
}

func TestParseCalibrationFromGcode_DoesNotMapInternalBridgeKeys(t *testing.T) {
	content := "; internal_bridge_flow = 1\n; internal_bridge_density = 100%\n; bridge_flow = 0.85\n; bridge_density = 90%\n"
	got := ParseCalibrationFromGcode([]byte(content), 0)
	if got["cal_bridge_flow_ratio"] != "0.85" {
		t.Errorf("cal_bridge_flow_ratio = %q, want %q (must match 'bridge_flow' not 'internal_bridge_flow')", got["cal_bridge_flow_ratio"], "0.85")
	}
	if got["cal_bridge_density"] != "90" {
		t.Errorf("cal_bridge_density = %q, want %q (must match 'bridge_density' not 'internal_bridge_density')", got["cal_bridge_density"], "90")
	}
}

// ── GetCalibrationCandidates / GetCalibrationSource ─────────────────────────────

func newCalibrationTestBridge(t *testing.T, spoolmanURL string) *FilamentBridge {
	t.Helper()
	t.Setenv("THE_MOMENT_DB_PATH", t.TempDir())
	t.Setenv("THE_MOMENT_GCODE_PATH", t.TempDir())
	bridge, err := NewFilamentBridge(nil)
	if err != nil {
		t.Fatalf("NewFilamentBridge: %v", err)
	}
	t.Cleanup(func() { bridge.Close() })
	if spoolmanURL != "" {
		bridge.spoolman = NewSpoolmanClient(spoolmanURL, 5)
	}
	return bridge
}

// mockSpoolmanServer serves GetAllSpools/GetSpoolByID for spool ID 42, filament ID 7.
func mockSpoolmanServer(t *testing.T) *httptest.Server {
	t.Helper()
	filamentJSON := `{"id":7,"name":"PolyMax PLA","material":"PLA"}`
	spoolJSON := fmt.Sprintf(`{"id":42,"filament":%s}`, filamentJSON)
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		switch {
		case r.URL.Path == "/api/v1/spool":
			fmt.Fprintf(w, "[%s]", spoolJSON)
		case r.URL.Path == "/api/v1/spool/42":
			fmt.Fprint(w, spoolJSON)
		default:
			http.NotFound(w, r)
		}
	}))
}

func TestGetCalibrationCandidates_FindsPrintWithGcodeAttachment(t *testing.T) {
	srv := mockSpoolmanServer(t)
	defer srv.Close()
	b := newCalibrationTestBridge(t, srv.URL)

	res, err := b.db.Exec(`
		INSERT INTO print_history
			(printer_name, toolhead_id, spool_id, filament_used,
			 print_started, print_finished, job_name, status)
		VALUES ('Core One L', 0, 42, 5.0, datetime('now'), datetime('now'), 'calibration_test.gcode', 'completed')`)
	if err != nil {
		t.Fatalf("insert print_history: %v", err)
	}
	printID64, _ := res.LastInsertId()
	printID := int(printID64)

	if err := b.savePrintFile(printID, "gcode", "calibration_test.gcode", "", []byte(sampleConfigDump)); err != nil {
		t.Fatalf("savePrintFile: %v", err)
	}

	candidates, err := b.GetCalibrationCandidates(7)
	if err != nil {
		t.Fatalf("GetCalibrationCandidates: %v", err)
	}
	if len(candidates) != 1 {
		t.Fatalf("got %d candidates, want 1: %+v", len(candidates), candidates)
	}
	if candidates[0].PrintID != printID {
		t.Errorf("candidate PrintID = %d, want %d", candidates[0].PrintID, printID)
	}
	if candidates[0].PrinterName != "Core One L" {
		t.Errorf("candidate PrinterName = %q, want %q", candidates[0].PrinterName, "Core One L")
	}
}

func TestGetCalibrationCandidates_ExcludesPrintsWithoutGcodeAttachment(t *testing.T) {
	srv := mockSpoolmanServer(t)
	defer srv.Close()
	b := newCalibrationTestBridge(t, srv.URL)

	if _, err := b.db.Exec(`
		INSERT INTO print_history
			(printer_name, toolhead_id, spool_id, filament_used,
			 print_started, print_finished, job_name, status)
		VALUES ('Core One L', 0, 42, 5.0, datetime('now'), datetime('now'), 'no_gcode.gcode', 'completed')`); err != nil {
		t.Fatalf("insert print_history: %v", err)
	}

	candidates, err := b.GetCalibrationCandidates(7)
	if err != nil {
		t.Fatalf("GetCalibrationCandidates: %v", err)
	}
	if len(candidates) != 0 {
		t.Fatalf("got %d candidates, want 0 (no gcode attachment saved): %+v", len(candidates), candidates)
	}
}

func TestGetCalibrationCandidates_ExcludesDifferentFilament(t *testing.T) {
	srv := mockSpoolmanServer(t)
	defer srv.Close()
	b := newCalibrationTestBridge(t, srv.URL)

	res, err := b.db.Exec(`
		INSERT INTO print_history
			(printer_name, toolhead_id, spool_id, filament_used,
			 print_started, print_finished, job_name, status)
		VALUES ('Core One L', 0, 42, 5.0, datetime('now'), datetime('now'), 'calibration_test.gcode', 'completed')`)
	if err != nil {
		t.Fatalf("insert print_history: %v", err)
	}
	printID, _ := res.LastInsertId()
	if err := b.savePrintFile(int(printID), "gcode", "calibration_test.gcode", "", []byte(sampleConfigDump)); err != nil {
		t.Fatalf("savePrintFile: %v", err)
	}

	// Query for a different filament ID (99) — spool 42 belongs to filament 7.
	candidates, err := b.GetCalibrationCandidates(99)
	if err != nil {
		t.Fatalf("GetCalibrationCandidates: %v", err)
	}
	if len(candidates) != 0 {
		t.Fatalf("got %d candidates, want 0 (spool belongs to a different filament): %+v", len(candidates), candidates)
	}
}

func TestGetCalibrationSource_ReadsAttachmentAndResolvesToolIndex(t *testing.T) {
	srv := mockSpoolmanServer(t)
	defer srv.Close()
	b := newCalibrationTestBridge(t, srv.URL)

	res, err := b.db.Exec(`
		INSERT INTO print_history
			(printer_name, toolhead_id, spool_id, filament_used,
			 print_started, print_finished, job_name, status)
		VALUES ('Core One L', 1, 42, 5.0, datetime('now'), datetime('now'), 'calibration_test.gcode', 'completed')`)
	if err != nil {
		t.Fatalf("insert print_history: %v", err)
	}
	printID64, _ := res.LastInsertId()
	printID := int(printID64)
	if err := b.savePrintFile(printID, "gcode", "calibration_test.gcode", "", []byte(sampleConfigDump)); err != nil {
		t.Fatalf("savePrintFile: %v", err)
	}

	content, toolIndex, err := b.GetCalibrationSource(7, printID)
	if err != nil {
		t.Fatalf("GetCalibrationSource: %v", err)
	}
	if toolIndex != 1 {
		t.Errorf("toolIndex = %d, want 1 (from print_history.toolhead_id)", toolIndex)
	}
	values := ParseCalibrationFromGcode(content, toolIndex)
	if values["cal_max_flow_rate"] != "16" {
		t.Errorf("cal_max_flow_rate = %q, want %q (toolIndex 1)", values["cal_max_flow_rate"], "16")
	}
}

func TestGetCalibrationSource_NoAttachmentReturnsError(t *testing.T) {
	srv := mockSpoolmanServer(t)
	defer srv.Close()
	b := newCalibrationTestBridge(t, srv.URL)

	res, err := b.db.Exec(`
		INSERT INTO print_history
			(printer_name, toolhead_id, spool_id, filament_used,
			 print_started, print_finished, job_name, status)
		VALUES ('Core One L', 0, 42, 5.0, datetime('now'), datetime('now'), 'no_gcode.gcode', 'completed')`)
	if err != nil {
		t.Fatalf("insert print_history: %v", err)
	}
	printID, _ := res.LastInsertId()

	if _, _, err := b.GetCalibrationSource(7, int(printID)); err == nil {
		t.Error("expected error for print with no gcode attachment, got nil")
	}
}
